### PR TITLE
add syncHandlerFunc for feedinventory controller

### PR DESCRIPTION
**Pull request by silenceper**
Signed-off-by: silenceper <silenceper@gmail.com>

#### What type of PR is this?

add syncHandlerFunc for feedinventory controller, make write External FeedInventory  easy

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by dixudx — COMMENTED** [review]
I don't see the reasons to update this controller.

**Comment by dixudx** [comment]
> add syncHandlerFunc for feedinventory controller, make write External FeedInventory easy

Please refer https://github.com/clusternet/sample-controllers/tree/main/cmd/external-feedinventory

**Comment by silenceper** [comment]
@dixudx Added customSyncHandlerFunc parameter to control the generation of `feedinventory `

**Comment by dixudx** [comment]
> @dixudx Added customSyncHandlerFunc parameter to control the generation of `feedinventory `

`FeedInventory` is an opt-in, which can be disabled by feature gate `FeedInventory`. Out-of-tree feedinventory controller is supported as well.

I still don't see the reasons for this PR change.

**Comment by silenceper** [comment]
The essence is to reuse the original code as much as possible, but at present I have realized the Out-of-tree feedinventory controller first, if don't need it, I will close this pr

**Comment by dixudx** [comment]
> The essence is to reuse the original code as much as possible, but at present I have realized the Out-of-tree feedinventory controller first, if don't need it, I will close this pr

@silenceper The initial version of feedinventory is quite simliar to this PR. With considerations of out-of-tree third-party resources and easy for use, we don't not define a `syncHandlerFunc` like other controllers.

**Review by dixudx — APPROVED** [review]

**Pull request merged**
