### PR TITLE
pass down cluster ID to replicas predictor

### PR DESCRIPTION
**Pull request by yiwei-C**
#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by lmxia** [comment]
I did't really get the usage of cluster ID  in predictor, maybe in a new PR? Do you mind make a little explanation.

**Comment by yiwei-C** [comment]
> I did't really get the usage of cluster ID  in predictor, maybe in a new PR? Do you mind make a little explanation.
> 
> 

In order to predict replicas for a group of clusters, the cluster ID needs to be passed to the predictor.

**Comment by dixudx** [comment]
> > I did't really get the usage of cluster ID  in predictor, maybe in a new PR? Do you mind make a little explanation.
> 
> In order to predict replicas for a group of clusters, the cluster ID needs to be passed to the predictor.

Yep. In Clusternet, we have flexible topologies (such as 1:1, 1:N and mixed) for the predictors. The Cluster ID here can be used by a predictor that serves multiple clusters.

**Review by dixudx — APPROVED** [review]
I'm ok with this change. Thanks.

**Review by lmxia — APPROVED** [review]
lgtm

**Pull request merged**
