### PR TITLE
bump controller-gen to v0.10.0

### LINKED ISSUE #613: bump controller-gen to v0.10.0

### PR DESCRIPTION
**Pull request by abstractmj**
Fixes #613

### CODE REVIEW

**Comment by abstractmj** [comment]
@dixudx please take a look

**Review by dixudx — CHANGES_REQUESTED** [review]
You should bump the version in `Makefile` as well.

**Comment by abstractmj** [comment]
@dixudx fixed

**Review by dixudx — APPROVED** [review]
Looks good to me.
Welcome to join the community!

**Pull request merged**
