### PR TITLE
no need enqueue when FeedInventory feature disable

### PR DESCRIPTION
**Pull request by silenceper**
Signed-off-by: silenceper <silenceper@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by dixudx — COMMENTED** [review]
The feedInventory controller will not be started when the feature gate FeedInventory is disabled.

https://github.com/clusternet/clusternet/blob/a4b9ac3f7d5e78205ee4a43f3035957cb7a6d52f/pkg/hub/deployer/deployer.go#L262-L265

**Comment by silenceper** [comment]
will it cause the `workqueue` to continue to grow?

**Comment by dixudx** [comment]
> will it cause the `workqueue` to continue to grow?

Yes. At least, the `queue` will watch all FeedInventory objects.

I'm fine with this change. Good catch. @silenceper

**Review by dixudx — APPROVED** [review]
This helps optimizing the cache of work queue. Good work!

**Pull request merged**
