### PR TITLE
populate legacy secret-based sa token

### LINKED ISSUE #500: k3s v1.24.6+k3s1 child cluster working abnormally
#### What happened:

when I upgrade  k3s version from v1.23.8+k3s2 to v1.24.6+k3s1，helm release  failed syncing to child cluster

logs on clusternet-agent

```
W1009 13:05:24.374070       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange
W1009 13:05:24.383964       1 clusterstatus_controller.go:259] failed to list podMetris with err: 0x24da820
W1009 13:05:24.385094       1 clusterstatus_controller.go:283] failed to list nodeMetris with err: 0x24da820
E1009 13:05:26.203675       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:31.818574       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:38.021635       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
W1009 13:05:43.676526       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
E1009 13:05:43.676571       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ServiceExport: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
W1009 13:05:44.392428       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange

```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`): v0.12.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.12.0
- Kubernetes version (use `kubectl version`): v1.24.6+k3s1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-126-generic

### PR DESCRIPTION
**Pull request by dixudx**
Signed-off-by: Di Xu <stephenhsu90@gmail.com>

#### What type of PR is this?
kind/bug

#### What this PR does / why we need it:
only for Kubernetes cluster >= v1.24.0

#### Which issue(s) this PR fixes:

Fixes #500

### CODE REVIEW

**Comment by dixudx** [comment]
@jasine Please help verify this PR.

**Comment by dixudx** [comment]
cc @Sad-polar-bear

**Comment by jasine** [comment]
@dixudx  ok, is there a latest tag to test?

**Comment by jasine** [comment]
@dixudx I build on master branch with commit `5f04f474619cefeb85642666698ae363bff28013` , still has this problem

```
E1019 06:19:01.904173       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
W1019 06:19:04.207693       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange
W1019 06:19:04.211273       1 clusterstatus_controller.go:259] failed to list podMetris with err: 0x24dab80
W1019 06:19:04.211634       1 clusterstatus_controller.go:283] failed to list nodeMetris with err: 0x24dab80
E1019 06:19:08.839395       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
E1019 06:19:15.456285       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
W1019 06:19:15.839327       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
E1019 06:19:15.839343       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ServiceExport: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
E1019 06:19:21.782716       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
W1019 06:19:24.220916       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange
W1019 06:19:24.224622       1 clusterstatus_controller.go:259] failed to list podMetris with err: 0x24dab80
W1019 06:19:24.224994       1 clusterstatus_controller.go:283] failed to list nodeMetris with err: 0x24dab80
E1019 06:19:28.778334       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
E1019 06:19:35.407478       1 wait.go:188] failed to get Secret clusternet-system/clusternet-app-deployer: secrets "clusternet-app-deployer" not found
```

**Comment by dixudx** [comment]
@jasine Please apply this file https://github.com/clusternet/clusternet/blob/main/deploy/agent/clusternet_agent_deployment.yaml again, which has been updated as well. Be remember to replace with your built image.

**Comment by jasine** [comment]
@dixudx sorry I omitted these resource

problems solved now

**Pull request merged**
