### PR TITLE
pass down extra headers with prefix clusternet

### LINKED ISSUE #488: Does clusternet support impersonate method  ?
#### Why is this needed:
I use clusternet to manage muti-cluster, but when I use impersonate method to access child-cluster, I get an error; by reading the source code of clusternet, I think clusternet does not support impersonate method.
#### What would you like to be added:
If this is true, are there plans to support impersonate methods? i mean : `Impersonate-User`, `Impersonate-Group` , and `Impersonate-Extra-`

### PR DESCRIPTION
**Pull request by dixudx**
#### What type of PR is this?
kind/feature

#### What this PR does / why we need it:
Extra headers prefixing with `clusternet` will be passed down when proxying `CONNECT`.
#### Which issue(s) this PR fixes:

Fixes #488

### CODE REVIEW

**Comment by yeqiugt** [comment]
> cc @yeqiugt Please try this fix.

This is a good idea, but still only partially solves the problem as it doesn't work when using `kubectl get ns --as=someone`

**Comment by dixudx** [comment]
> > cc @yeqiugt Please try this fix.
> 
> This is a good idea, but still only partially solves the problem as it doesn't work when using `kubectl get ns --as=someone`

Currently kubectl does not provide options for extra fields. So you can configure it with a kubeconfig file instead, where you can set fiedls in `extras`.

**Comment by dixudx** [comment]
> This is a good idea, but still only partially solves the problem as it doesn't work when using `kubectl get ns --as=someone`

clusternet/kubectl-clusternet#6 added flags on client-side to use for child cluster impersonation, which could be used with `kubectl clusternet --child-kubeconfig-xxx --cluster-id=xxx --clusternet-as=xxx`

**Comment by dixudx** [comment]
Already released `kubectl-clusternet` v0.8.0. Follow [this guide](https://github.com/clusternet/kubectl-clusternet#install-with-krew) to install or upgrade this plugin.

**Pull request merged**
