### PR TITLE
dryrun support for child clusters

### LINKED ISSUE #457: dry run support for managed cluster
#### What happened:
when i do a kubectl dry run command to the k8s cluster managed by clusternet ，there goes an error: dry run is not supported;     

I think  maybe this is a problem  caused by remote-dialer.clientDial.newConnect ? or rejected by aggregated apiserver ?  the response time is very short，such as 1ms/2ms，so it probably happened  in the clusternet-hub side；

Is there a plan to support dry-run method？

image

#### What you expected to happen:
user can use  dry run command  to cluster managed  by clusternet 
#### How to reproduce it (as minimally and precisely as possible):
1、register  a cluster by  deploy clusternet-agent；
2、make a proxy kubeconfig  to access  the cluster   through clusternet-hub；
3、 kubectl create  ns  test  --kubeconfig=proxyconfig  --dry-run=server -v=9

#### Environment:
- Clusternet version: v0.10

- Kubernetes version (use `kubectl version`): v1.20.10

### PR DESCRIPTION
**Pull request by yeqiugt**
#### What type of PR is this?
kind/enhancement

#### What this PR does / why we need it:
edit go.mod to refer the latest version of github.com/clusternet/apiserver:release-1.23-clusternet
#### Which issue(s) this PR fixes:

Fixes #457

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
Nice work! Thanks.

**Comment by dixudx** [comment]
@yeqiugt Please rebase your codes with clusternet main branch.

**Comment by yeqiugt** [comment]
> @yeqiugt Please rebase your codes with clusternet main branch.

i add reomte upstream by doing this "git remote add upstream https://github.com/clusternet/clusternet". after that,  use "rebase" and "force push", but i don't know whether it would work

**Comment by yeqiugt** [comment]
It seems didn't work. Sorry about to see that,  if it is diffcult to solve, can i close this pr and ceate a new one ?

**Comment by dixudx** [comment]
> It seems didn't work. Sorry about to see that, if it is diffcult to solve, can i close this pr and ceate a new one ?

It seems the codes had not been rebased correctly.

Feel free to use this pr or open a new one.

**Pull request closed without merging**
