### PR TITLE
add helm options upgradeAtomic parameter

### LINKED ISSUE #625: support atomic param to be set separately during install helmrelease and upgrade helmrelease
#### What would you like to be added:
support atomic param to be set separately during install and upgrade

#### Why is this needed:
Currently, the atomic parameter applies uniformly to the installation and upgrade process, which is not very flexible. It is hoped that the atomic param during install and the atomic param during upgrade can be set separately. This can support scenarios where the values to be set for atomic are different between install and upgrade.

### PR DESCRIPTION
**Pull request by wl-chen**
#### What type of PR is this?
kind/feature

#### Which issue(s) this PR fixes:

Fixes #625

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
Good work! Welcome to the community.

**Comment by wl-chen** [comment]
> @wl-chen Would you please run `make generated` to update all the generated files. Thanks.

i ran `make generated`, but failed. The output show that:
```
Generating CRDs at manifests/crds
Generating deepcopy funcs
F0323 17:27:05.642928   41217 main.go:83] Error: Failed executing generator: some packages had errors:
errors in package "github.com/clusternet/clusternet/pkg/apis/apps/v1alpha1":
open ../../../github.com/clusternet/clusternet/pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go: no such file or directory

errors in package "github.com/clusternet/clusternet/pkg/apis/clusters/v1beta1":
open ../../../github.com/clusternet/clusternet/pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go: no such file or directory

errors in package "github.com/clusternet/clusternet/pkg/apis/proxies/v1alpha1":
open ../../../github.com/clusternet/clusternet/pkg/apis/proxies/v1alpha1/zz_generated.deepcopy.go: no such file or directory

make: *** [generated] Error 255

```
somethings wrong in makefile?

**Comment by wl-chen** [comment]
> outdated.



> @wl-chen Maybe your local `controller-gen` are outdated.
> 
> No worries. I've created another PR #637 to help address the auto-generated issues here.

@dixudx my controller-gen version is v0.10.0, is same as clusternet. And i execute `make generated`, then shows error:
```
Generating OpenAPI definitions for proxies:v1alpha1 at github.com/clusternet/clusternet/pkg/generated/openapi
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroup,ServerAddressByClientCIDRs
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroup,Versions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroupList,Groups
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResource,Categories
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResource,ShortNames
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResourceList,APIResources
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIVersions,ServerAddressByClientCIDRs
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIVersions,Versions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,ApplyOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,CreateOptions,DryRun
...
```
u know why~~~?

**Comment by dixudx** [comment]
@wl-chen What's your Golang version? And please make sure you've got all the go modules in your local env by running `go mod vendor`.

**Comment by wl-chen** [comment]
> go mod vendor

@dixudx I executed `go mod vender` before `make generated`, and go version is `go1.19.7 linux/amd64`.

**Comment by dixudx** [comment]
> > go mod vendor
> 
> @dixudx I executed `go mod vender` before `make generated`, and go version is `go1.19.7 linux/amd64`.

That's weird.

**Comment by wl-chen** [comment]
> > > go mod vendor
> > 
> > 
> > @dixudx I executed `go mod vender` before `make generated`, and go version is `go1.19.7 linux/amd64`.
> 
> That's weird.

@dixudx But i check k8s.io/apimachinery code(version v0.25.6, the clusternet is) indeed lacks `+listtype` note. And controller-gen(version v0.10.0) will check this.

**Comment by dixudx** [comment]
> But i check k8s.io/apimachinery code(version v0.25.6, the clusternet is) indeed lacks `+listtype` note. And controller-gen(version v0.10.0) will check this.

[The CI job](https://github.com/clusternet/clusternet/actions/runs/4499215015/jobs/7917411743) using binary `controller-gen` (version v0.10.0)  also complained the missing updates of those generated files.

**Comment by wl-chen** [comment]
> > But i check k8s.io/apimachinery code(version v0.25.6, the clusternet is) indeed lacks `+listtype` note. And controller-gen(version v0.10.0) will check this.
> 
> [The CI job](https://github.com/clusternet/clusternet/actions/runs/4499215015/jobs/7917411743) using binary `controller-gen` (version v0.10.0) also complained the missing updates of those generated files.

@dixudx yes. and i think it's maybe a bug in makefile, cuz i reproduce this in another machine. But how did you generage auto-generate file(#637)? Am i somewhere wrong when i execute `make generated`?

**Comment by dixudx** [comment]
Would you please execute below commands to clean up the environment.

```bash
go clean -modcache
rm $(which controller-gen)
```

Also please make sure that repo `clusternet/clusternet` is available in the `$GOPATH/src/github.com/clusternet` directory.

And then run `make generated`.

In our CI pipelines, all works well.

**Comment by wl-chen** [comment]
> 



> Would you please execute below commands to clean up the environment.
> 
> ```shell
> go clean -modcache
> rm $(which controller-gen)
> ```
> 
> Also please make sure that repo `clusternet/clusternet` is available in the `$GOPATH/src/github.com/clusternet` directory.
> 
> And then run `make generated`.
> 
> In our CI pipelines, all works well.

@dixudx I check it's ok. Maybe my env is wrong, although i don't know anywhere wrong. I'll do some more research.

**Pull request merged**
